test2

diff --git a/.github/workflows/server-ci.yml b/.github/workflows/server-ci.yml
--- a/.github/workflows/server-ci.yml
+++ b/.github/workflows/server-ci.yml
@@ -82,6 +82,11 @@ jobs:
               exit 1
           fi
 
+           if [ "$STATUS" = "build_failed" ]; then
+              echo "❌ Deployment failed!"
+              exit 1
+          fi
+
           sleep 15
           done
 
